# Generated by Django 4.2 on 2023-05-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='camera_details',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
