# Generated by Django 4.2 on 2023-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_profile_camera_details_profile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
