# Generated by Django 4.2 on 2023-05-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
